default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ChatterBox_development

test:
  <<: *default
  database: ChatterBox_test

production:
  <<: *default
  database: ChatterBox_production
  username: ChatterBox
  password: <%= ENV['CHATTERBOX_DATABASE_PASSWORD'] %>
#     url: <%= ENV['CHATTERBOX_DATABASE_URL'] %>
